version: '2'
services:
  ubuntu1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka0:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka0
      KAFKA_CREATE_TOPICS: "booster-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: ubuntu1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
