version: '2'

networks:
  exchange:
    external:
      name: exchange-net

services:

  ca.nuriorg.exchange.com:
    image: hyperledger/fabric-ca:$HF_IMAGE_VERSION
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=exchange-net
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.nuriorg.exchange.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.nuriorg.exchange.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.nuriorg.exchange.com_sk
    ports:
      - 17054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/nuriorg.exchange.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.nuriorg.exchange.com
    networks:
      - exchange

  peer0.nuriorg.exchange.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer0.nuriorg.exchange.com
    environment:
      - CORE_PEER_ID=peer0.nuriorg.exchange.com
      - CORE_PEER_ADDRESS=peer0.nuriorg.exchange.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nuriorg.exchange.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nuriorg.exchange.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nuriorg.exchange.com:7051
      - CORE_PEER_LOCALMSPID=NuriOrgMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.nuriorg.exchange.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb0.nuriorg.exchange.com
    ports:
      - 7051:7051
      # prometheus metrics port
      - 9443:9443
    volumes:
      - ../crypto-config/peerOrganizations/nuriorg.exchange.com/peers/peer0.nuriorg.exchange.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/nuriorg.exchange.com/peers/peer0.nuriorg.exchange.com/tls:/etc/hyperledger/fabric/tls
      - ../volumes/peer0.nuriorg.exchange.com:/var/hyperledger/production

  couchdb0.nuriorg.exchange.com:
    container_name: couchdb0.nuriorg.exchange.com
    image: hyperledger/fabric-couchdb:$HF_TOOL_IMAGE_VERSION
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    volumes:
      - ../volumes/couchdb0.nuriorg.exchange.com:/opt/couchdb/data
    networks:
      - exchange
