version: '2'


networks:
  exchange:
    external:
      name: exchange-net

services:

  ca.exchange.com:
    image: hyperledger/fabric-ca:${FABRIC_IMG_TAG}
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=exchange-net
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.exchange.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.exchange.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d56e4a4d2b14501bb51376cf1d1521d12afadc3010a6d79d21e62c04ebbb5358_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/ordererOrganizations/exchange.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.exchange.com
    networks:
      - exchange
