# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # MjmallOrderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: exchange.com
    Template:
      Count: 4
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Store1
  # ---------------------------------------------------------------------------
  - Name: NuriOrg
    Domain: nuriorg.exchange.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
  # ---------------------------------------------------------------------------
  # Org2: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: NFlexOrg
    Domain: nflexorg.exchange.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
