version: '2'

networks:
  exchange:
    external:
      name: exchange-net

services:
  peer1.nflexorg.exchange.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer1.nflexorg.exchange.com
    environment:
      - CORE_PEER_ID=peer1.nflexorg.exchange.com
      - CORE_PEER_ADDRESS=peer1.nflexorg.exchange.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      # - CORE_PEER_CHAINCODEADDRESS=peer1.nflexorg.exchange.com:7052
      # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nflexorg.exchange.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nflexorg.exchange.com:10051
      - CORE_PEER_LOCALMSPID=NFlexOrgMSP
    ports:
      - 10051:7051
      - 10053:7053
      - 9446:9443
      # - '47051:7051'
      # - '47053:7053'
    volumes:
      - ./crypto-config/peerOrganizations/nflexorg.exchange.com/peers/peer1.nflexorg.exchange.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/nflexorg.exchange.com/peers/peer1.nflexorg.exchange.com/tls:/etc/hyperledger/fabric/tls
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:${FABRIC_IMG_TAG}
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_DOCKER_HOSTCOFIG_NETWORKMODE=exchange-net
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.nuriorg.exchange.com:7051
      - CORE_PEER_LOCALMSPID=NuroOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nuriorg.exchange.com/peers/peer0.nuriorg.exchange.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nuriorg.exchange.com/peers/peer0.nuriorg.exchange.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nuriorg.exchange.com/peers/peer0.nuriorg.exchange.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nuriorg.exchange.com/users/Admin@nuriorg.exchange.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash #-c "scripts/scripts.sh exchangecc"
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - exchange
