version: '2'

networks:
  exchange:
    external:
      name: exchange-net

services:

  ca.nflexorg.exchange.com:
    image: hyperledger/fabric-ca:${FABRIC_IMG_TAG}
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=exchange-net
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.nflexorg.exchange.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.nflexorg.exchange.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ced25bdd2991f0fa3fd6021be9aeb0008b7d5fc9a43c3ad4ecb4a44b21787ffd_sk
    ports:
      - "27054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/nflexorg.exchange.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.nflexorg.exchange.com
    networks:
      - exchange

  peer0.nflexorg.exchange.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer0.nflexorg.exchange.com
    environment:
      - CORE_PEER_ID=peer0.nflexorg.exchange.com
      - CORE_PEER_ADDRESS=peer0.nflexorg.exchange.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      # - CORE_PEER_CHAINCODEADDRESS=peer0.nflexorg.exchange.com:7052
      # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nflexorg.exchange.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nflexorg.exchange.com:9051
      - CORE_PEER_LOCALMSPID=NFlexOrgMSP
    ports:
      - 9051:7051
      - 9053:7053
      - 9445:9443
      # - '37051:7051'
      # - '37053:7053'
    volumes:
      - ./crypto-config/peerOrganizations/nflexorg.exchange.com/peers/peer0.nflexorg.exchange.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/nflexorg.exchange.com/peers/peer0.nflexorg.exchange.com/tls:/etc/hyperledger/fabric/tls
