version: '2'

services:
  zookeeper-base:
    image: hyperledger/fabric-zookeeper:${EXT_IMG_TAG}
    restart: always
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=exchange-net
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
      # - ZOO_SERVERS=server.1=zookeeper0:2888:3888
    ports:
      - '2181'
      - '2888'
      - '3888'
    networks:
      - exchange