version: '2'


fabric:
  chaincodeInstall: false
  ordererID: orderer0.exchange.com
  channelID: exchange-channel
  channelConfig: ./configs/channel.tx
  chainCodeID: exchange
  chainCodePath: github.com/chaincode/exchange-ex
  orgAdmin: Admin
  orgName: NuriOrg
  configFile: ./configs/config.yaml
  userName: User1


kafka:
  version: 1.0.0
  brokers: kafka0:9092
  topics: booster-topic
  producerClientID: TxBooster_Producer
  consumerClientID: TxBooster_Consumer
  consumerGroupID: boosterConsumerGroup
  offsetOldest: true
  logOutput: true


# deprecated
#redis:
#  ip: localhost
#  port: 6379
#  auth: true
#  password: bigsize


mongodb:
  ip: localhost
  port: 27017
  database: exchange
  collection: ledger

batch:
  count: 50
  lingerMs: 1000
  maxBytesPerTx: 128
