core:
    client-request-timeout: 45000
    tx-update-time: 1000

    skipStartScript: false
    skipEndScript: false

    logging:
      consolelogger:
        target: console
        level: info
      filelogger:
        target: daily-rotate-file
        level: info
        filename: log/caliper-%DATE%.log
        datePattern: YYYY-MM-DD-HH
        maxSize: 5m
        zippedArchive: true
# socket-io server information
socket-io:
    host: http://localhost
    port: 4000
fabricCcp:
    sleepAfter:
        createChannel: 5000
        joinChannel: 5000
        instantiateChaincode: 5000
    verify:
        proposalResponse: false
        readWriteSets: true
    timeout:
        chaincodeInstantiate: 300000
        chaincodeInstantiateEvent: 100000
        invokeOrQuery: 60000
    loadBalancing: tx
    overwriteGopath: true
    latencyThreshold: 1.0
    countQueryAsLoad: true
fabric:
sawtooth:


