version: '2'

services:
  # zookeeper-base:
  #   image: hyperledger/fabric-zookeeper
  #   restart: always
  #   environment:
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=exchange-net
  #     - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
  #     # - ZOO_SERVERS=server.1=zookeeper0:2888:3888
  #   ports:
  #     - '2181'
  #     - '2888'
  #     - '3888'
  #   networks:
  #     - exchange

  kafka-base:
    image: hyperledger/fabric-kafka:$HF_TOOL_IMAGE_VERSION
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"
    restart: always
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=exchange-net
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      # - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 *1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_LECTION_ENABLE=false
    networks:
      - exchange

