version: '2'

services:
  zookeeper-base:
    image: hyperledger/fabric-zookeeper:$HF_TOOL_IMAGE_VERSION
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"
    restart: always
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=exchange-net
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
      # - ZOO_SERVERS=server.1=zookeeper0:2888:3888
    ports:
      - '2181'
      - '2888'
      - '3888'
    networks:
      - exchange
